# Generated by Django 4.0.2 on 2022-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_price', models.CharField(max_length=100)),
                ('Selling_price', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=100)),
            ],
        ),
    ]
